### ISSUE TITLE
windows cannot find the file 'pathonw'. Please make sure the file name is correct and try again. what is the reason for this error

### ISSUE THREAD

**Issue by VrahVishnulok** [LittleHugeUnicorn/FPS-AI-Aiming#1]
By the way, a library is missing：screeninfo

**Comment by LittleHugeUnicorn** [comment]
Thank you for your correction~

**Comment by UNIkeEN** [comment]
Thank you for your correction~ screeninfo is add to requirements list

**Comment by VrahVishnulok** [comment]
windows cannot find the file 'pathonw'.

**Comment by VrahVishnulok** [comment]
windows cannot find the file 'pathonw'.

**Comment by LittleHugeUnicorn** [comment]
‘Pythonw’ is a command to run python script without opening the console window. If this problem occurs, you can check your python installation, or change the ‘pythonw'  in the code to python.

**Comment by UNIkeEN** [comment]
Do you mean 'pythonw'?
‘Pythonw’ is a command to run python script without opening the console window. If this problem occurs, you can check your python installation, or change the ‘pythonw' in the code to python.
I cannot remember using the code ' pathonw'

**Comment by VrahVishnulok** [comment]
May I know your email address, I want to ask some questions！

**Comment by VrahVishnulok** [comment]
What environment are you running in? Can you be more specific? I want to know what versions of cuda, pytorch, and python you are using. And If possible, can you also tell me what version of your dependency packages are? You just  to take a screenshot in the settings to see the version of the package.

**Comment by UNIkeEN** [comment]
I run in Python 3.9 and all the packages is the latest version from pypi.

**Comment by VrahVishnulok** [comment]
The environment has been built but the operation has no effect, show_info: None is displayed, which function is this command in?
