### ISSUE TITLE
没有hubconf.py文件

### ISSUE THREAD

**Issue by ZhiYhi** [LittleHugeUnicorn/FPS-AI-Aiming#3]
FileNotFoundError: [Errno 2] No such file or directory: 'xxxx:\xxxx\\xxxx\\Downloads\\xxxxx\\FPS-AI-Aiming-main\\bin\\ultralytics\\yolov5\\hubconf.py'   没有hubconf.py文件    作者有空麻烦发到1435244588@qq.com邮箱上感谢！

**Comment by UNIkeEN** [comment]
很抱歉，之前我们将本地已下载的第三方预训练模型也一并上传到了仓库，现在我们重新整理了文件目录，您可以在运行时重新下载 yolov5 预训练模型，以避免可能的文件缺失。

如果您还遇到了此类问题，请再次联系我~
