### ISSUE TITLE
程序正常运行，实际没有反应

### ISSUE THREAD

**Issue by as3124** [LittleHugeUnicorn/FPS-AI-Aiming#4]
launcher_0.3.6.py可以正常运行，ai_0.3.2也可以正常运行，且在游戏内按“X”键也会反馈“biu~”，但是实际上鼠标并没有移动进行瞄准，程序应该是正常运行了游戏内帧数下降了200~300帧。请问还有哪里可以进行排查呢？

**Comment by as3124** [comment]
请问可以发一下完整的conda list吗，我感觉还是配置问题

**Comment by UNIkeEN** [comment]
很抱歉，这是之前选修课的作业项目，当时的 conda 环境已经删除。

与鼠标操作的相关库是 pydirectinput ，您可以检查其版本或采取其他控制鼠标的库；您也可以先打开演示模式，排查人物检测是否成功。

**Comment by as3124** [comment]
感谢

**Comment by UNIkeEN** [comment]
不客气～
